@host = http://localhost:5000/api/v1/


###
POST {{host}}auth/sign-up HTTP/1.1
content-type: application/json

{
    "firstName": "Hasnain",
    "lastName": "Nisan",
    "email": "nisan@tastyTreat.com",
    "password": "password"
}

###
POST {{host}} HTTP/1.1
content-type: application/json

{
    "creator": "",
    "title": "",
    "message": "",
    "tags": "",
    "file": ""
}